list:
  ukraine_timemap:
    url: https://github.com/kamangir/blue-geo?ukraine-timemap-
    callable: ukraine_timemap
    association: bellingcat
  vancouver_watching:
    url: https://github.com/kamangir/Vancouver-Watching
    callable: vancouver_watching
  vis_tj_kg_map_2022:
    url: https://github.com/bellingcat/vis-tj-kg-map-2022
    callable: not_available
    comments: before/after non-geo-tagged high-res images of conflict zones.
associations:
  bellingcat:
    urls:
      - https://www.bellingcat.com/
      - https://github.com/bellingcat
  informnapalm:
    urls:
      - https://informnapalm.org/en/
