list:
  ukraine_timemap:
    url: https://github.com/kamangir/blue-geo?ukraine-timemap-
    callable: ukraine_timemap
    association: bellingcat
  vancouver_watching:
    url: https://github.com/kamangir/Vancouver-Watching
    callable: vancouver_watching
associations:
  bellingcat:
    urls:
      - https://www.bellingcat.com/
      - https://github.com/bellingcat
  informnapalm:
    urls:
      - https://informnapalm.org/en/
